-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "consecutiveLosses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cooldownUntil" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Trade" ADD COLUMN     "riskPercent" DOUBLE PRECISION,
ADD COLUMN     "takeProfitLevels" JSONB;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyLossLimit" DOUBLE PRECISION NOT NULL DEFAULT -0.08,
ADD COLUMN     "maxDrawdown" DOUBLE PRECISION NOT NULL DEFAULT -0.20,
ADD COLUMN     "maxExposure" DOUBLE PRECISION NOT NULL DEFAULT 0.20,
ADD COLUMN     "maxRiskPerTrade" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
ADD COLUMN     "peakBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "riskLocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "riskLockedAt" TIMESTAMP(3),
ADD COLUMN     "riskLockedReason" TEXT;
